/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flight.managment.system;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import static flight.managment.system.MySqlConfigration.connect;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monirozzaman.rony
 */
public class MyBookingLIstPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyBookingLIstPanel
     */
    public MyBookingLIstPanel() {
        initComponents();
        configDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myBookingList = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 0, 153));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("My Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        myBookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        myBookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myBookingListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(myBookingList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(395, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myBookingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBookingListMouseClicked
        int row = myBookingList.rowAtPoint(evt.getPoint());
        int col = myBookingList.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {
            String selectedFlightId = myBookingList.getValueAt(row, 0).toString();
            String[] choices = {"Delete"};
            String input = (String) JOptionPane.showInputDialog(null, "Please, make your choice", "Setting", JOptionPane.QUESTION_MESSAGE, null, choices, choices[0]);

            switch (input.toLowerCase()) {
                case "delete":
                    deleteFlightByFlightId(selectedFlightId);
                    break;

                default:
                    break;
            }
        }
    }//GEN-LAST:event_myBookingListMouseClicked
    private void configDisplay() {
        this.setPreferredSize(new Dimension(790, 586));
        this.setVisible(true);

        showBookingInTable();
    }

    public void showBookingInTable() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Flight Id", "Flight Title", "From", "To", "Date", "Time", "Description"}, 0);
        Connection conn = MySqlConfigration.connect();
        try {
            Statement statement = (Statement) conn.createStatement();
            ResultSet resultSet = statement.executeQuery("Select * From flight_user");

            while (resultSet.next()) {
                if (resultSet.getString("userId").equals(LoggedUserDetails.loggedUserId)) {
                    ResultSet flightDetails = statement.executeQuery("Select * From flight WHERE flightId = '" + resultSet.getString("flightId") + "'");
                    while (flightDetails.next()) {
                        model.addRow(new String[]{flightDetails.getString("flightId"), flightDetails.getString("flightTitle"), flightDetails.getString("flightFrom"), flightDetails.getString("flightTo"), flightDetails.getString("flightDate"), flightDetails.getString("flightTime"), flightDetails.getString("description")});
                    }
                    flightDetails.close();
                }

            }
            resultSet.close();
            MySqlConfigration.disconnect();
        } catch (SQLException ex) {
            System.err.println(ex);
        }

        myBookingList.setModel(model);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myBookingList;
    // End of variables declaration//GEN-END:variables

    private void deleteFlightByFlightId(String selectedFlightId) {
        Connection connection = MySqlConfigration.connect();
        try {
            Statement statement = (Statement) connect().createStatement();
            statement.execute("DELETE FROM flight_user WHERE flightId = '" + selectedFlightId + "'");
            statement.close();
            MySqlConfigration.disconnect();
            JOptionPane.showMessageDialog(null, "Removed");
            showBookingInTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Somthing is worng");
            System.err.println(ex);
        }
    }
}
